source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SlotLabel_Example', :exclusive => true do
  pod 'SlotLabel', :path => '../'
end

target 'SlotLabel_Tests', :exclusive => true do
  pod 'SlotLabel', :path => '../'

  
end
